[package]
name = "raytracing-in-one-weekend"
version = "0.1.0"
edition = "2021"

[dependencies]
cgmath =  "0.18.0"
image = "0.24.0"
ndarray = { version = "0.15.4", features = ["rayon"] }
rand = "0.8.4"
rayon = "1.5.1"

[profile.release]
debug = true
lto = "fat"
